CREATE TABLE "animals" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar UNIQUE,
                          "type" varchar,
                          "health" varchar,
                          "age" int,
                          "deleted" boolean DEFAULT false
);

CREATE TABLE "sightings" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "animal_id" int,
                          "location" varchar,
                          "ranger_name" varchar,
                          "deleted" boolean DEFAULT false
);

ALTER TABLE "sightings" ADD FOREIGN KEY ("animal_id") references "animals" ("id");


-- Sample Animals
INSERT INTO strength (name, score) VALUES ('FEARLESS', 10);
INSERT INTO strength (name, score) VALUES ('RUNNING', 10);
INSERT INTO strength (name, score) VALUES ('WEAPONS', 20);
INSERT INTO strength (name, score) VALUES ('KARATE', 5);

--Sample Sightings

INSERT INTO weakness (name, score) VALUES ('FEAR', -20);
INSERT INTO weakness (name, score) VALUES ('VENOM', -10);
INSERT INTO weakness (name, score) VALUES ('HEIGHTS', -20);
INSERT INTO weakness (name, score) VALUES ('SUN', 5);
